version: "3.8"

services:
  web:
    build: .
    ports:
      - "8500:8500"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1